Minor updates to syntax (#96)
* Update editor.h

Otherwise, compiling with header-only gives:

`gui/zep/include/zep/editor.h:439:51: error: copying member subobject of type 'std::atomic<bool>' invokes deleted constructor
    mutable std::atomic<bool> m_bPendingRefresh = true;`

* Update filesystem.cpp

* Create app_config.h

* updated conditional filesystem sourcing syntax for apple